version: "3.8"

services:
  ambev.developerevaluation.webapi:
    profiles:
      - disabled
  
  ambev.developerevaluation.database:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: DeveloperEvaluation
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  ambev.developerevaluation.nosql:
    ports:
      - "27017:27017"   
    environment:
        MONGO_INITDB_ROOT_PASSWORD: evAluAt10n
    volumes:
      - mongo_data:/data/db

  ambev.developerevaluation.cache:
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: 
  mongo_data:

